### ISSUE TITLE
master is broken, newly built binaries are crashing on AMD64_LINUX, AMD64_DARWIN, probably elsewhere too

### ISSUE THREAD

**Issue by dragisha** [modula3/cm3#10]
I have just found a culprit for a compiler crash, when built from HEAD. It is this commit:

commit ce1cfdd36ecc04559ff9c91fbed75588c77cb8cf
Author: Jay Krell <jay.krell@cornell.edu>
Date:   Mon Jan 11 19:20:29 2016 -0800

    Go ahead and alloca the jmpbufs.

Commit before this (3db9e85076bac18605ee3d9012b197e1daa1e732) does not crash, at least.

**Comment by dragisha** [comment]
I have just reverted this commit so master can be usable again. We can find out why alloca jmpbuf didn't work.

**Comment by jaykrell** [comment]
Were you building in the correct order, e.g. with upgrade.py?

This change changed the compiler/runtime interface and such absolutely required the correct order of building, that upgrade.py does, else would crash.

I would really like to keep this change.
It is a step toward making the system more portable.

�- Jay


________________________________

**Comment by dragisha** [comment]
I fully agree with you on this change - it looks great to me.
So, I first need to do an upgrade.py invocation, and then anything else I want?

**Comment by jaykrell** [comment]
It is true you have to rebuild everything. See also upgrade-full. I suppose I could allow for "interworking" old and new, perhaps, but unlikely.

 - Jay

**Comment by jaykrell** [comment]
Dragisha, I had at the time very high confidence in this change, and that confidence has not dropped.

It absolutely requires rebuildng the compiler and runtime in *the usual required order*.

There is nothing special about this change that isn't already a known situation, that many other changes are in.

That is -- there is no special casing, no special ordering, there is just one way to do things correctly.

There are other orders that can work when you have no changes, but in the face of changes, there is one way to do things.

Just that such changes don't happen often.

With all that said, I would like to just back my change.

This change is important toward the goal of reducing variation in the C backend output, i.e. to make it just posix32le, posix64le, posix32be, posix32le, and no more Linux/FreeBSD/Solaris/Darwin/OpenBSD variation.


�- Jay


________________________________
> From: jay.krell@cornell.edu 
> CC: cm3@noreply.github.com; jay.krell@cornell.edu 
> Subject: Re: [cm3] master is broken, newly built binaries are crashing 
> on AMD64_LINUX, AMD64_DARWIN, probably elsewhere too (#10) 
> Date: Sat, 26 Mar 2016 19:10:32 -0700 
> To: 
> reply@reply.github.com 
> 
> It is true you have to rebuild everything. See also upgrade-full. I 
> suppose I could allow for "interworking" old and new, perhaps, but 
> unlikely. 
> 
> - Jay 
> 
> On Mar 26, 2016, at 6:11 AM, dragisha

**Comment by jaykrell** [comment]
I tested this again, this time on I386_LINUX, and it worked -- commited.

�- Jay


----------------------------------------
> From: jay.krell@cornell.edu
> To: reply@reply.github.com
> CC: cm3@noreply.github.com
> Subject: RE: [cm3] master is broken, newly built binaries are crashing on AMD64_LINUX, AMD64_DARWIN, probably elsewhere too (#10)
> Date: Sat, 25 Jun 2016 23:26:58 +0000
>
> Dragisha, I had at the time very high confidence in this change, and that confidence has not dropped.
>
> It absolutely requires rebuildng the compiler and runtime in *the usual required order*.
>
> There is nothing special about this change that isn't already a known situation, that many other changes are in.
>
> That is -- there is no special casing, no special ordering, there is just one way to do things correctly.
>
> There are other orders that can work when you have no changes, but in the face of changes, there is one way to do things.
>
> Just that such changes don't happen often.
>
> With all that said, I would like to just back my change.
>
> This change is important toward the goal of reducing variation in the C backend output, i.e. to make it just posix32le, posix64le, posix32be, posix32le, and no more Linux/FreeBSD/Solaris/Darwin/OpenBSD variation.
>
>
> - Jay
>
>
> ________________________________
>> From: jay.krell@cornell.edu
>> CC: cm3@noreply.github.com; jay.krell@cornell.edu
>> Subject: Re: [cm3] master is broken, newly built binaries are crashing
>> on AMD64_LINUX, AMD64_DARWIN, probably elsewhere too (#10)
>> Date: Sat, 26 Mar 2016 19:10:32 -0700
>> To:
>> reply@reply.github.com
>>
>> It is true you have to rebuild everything. See also upgrade-full. I
>> suppose I could allow for "interworking" old and new, perhaps, but
>> unlikely.
>>
>> - Jay
>>
>> On Mar 26, 2016, at 6:11 AM, dragisha

**Comment by dragisha** [comment]
Hi Jay,

Please do it. I have verified this change by full rebuild, and I was sure I reverted my revert…. And I am using it for some time now, works great.

Thanks,
dd

--
Dragiša Durić
dragisha@m3w.org
