### ISSUE TITLE
Python 2 or Python 3?

### ISSUE THREAD

**Issue by 3oheicrw** [modula3/cm3#1033]
Which document should be followed?

https://github.com/modula3/cm3/blob/master/getting-started-windows.txt

https://github.com/modula3/cm3/wiki/Getting-Started%3A-Windows

**Comment by 3oheicrw** [comment]
Update: this document (https://github.com/modula3/cm3/blob/master/getting-started-windows.txt) is outdated, all of the Python scripts were updated to Python3 and this document (https://github.com/modula3/cm3/wiki/Getting-Started%3A-Windows) should be followed instead.

**Comment by VictorMiasnikov** [comment]
} document (https://github.com/modula3/cm3/blob/master/getting-started-windows.txt) is outdated
In fact: this document still actual for targets AMD64_NT , I386_NT.

Python3 concierge.py is alternative method.

I tested concierge.py for AMD64_LINUX target.

**Comment by VictorMiasnikov** [comment]
} all of the Python scripts were updated

But not all of the Python scripts work good after this ;-(
