### ISSUE TITLE
How to get cm3 ready and working with GCC?

### ISSUE THREAD

**Issue by 3oheicrw** [modula3/cm3#1034]
This document here said Visual Studio is needed. I don't want to install Visual Studio and GCC was said to be also supported so I want to use cm3 with GCC on my Windows. I'm using winlibs.com GCC build, but if MSYS2 is required I could install MSYS2 too.

https://github.com/modula3/cm3/wiki/Getting-Started%3A-Windows

**Comment by 3oheicrw** [comment]
Update: the information regarding MSYS2 is right on the document above, it's my mistake. Sorry.

**Comment by 3oheicrw** [comment]
Winlibs.com GCC builds were designed to use with MSYS2 but if we are on MSYS2 why don't just use it GCC packages instead? Everything will be easier to be managed by just the pacman package manager. BTW, there seems to be a POSIX environment is needed so we will need MSYS2 (a distribution of MinGW-W64 alone like Winlibs.com's builds are not enough).

**Comment by VictorMiasnikov** [comment]
} Visual Studio is needed
We are need some libs and "build tools" from / related Visual Studio for targets AMD64_NT, I386_NT.
We can choice between cl.exe and clang.exe

} MSYS2 (a distribution of MinGW-W64

 MinGW environment is need for targets  AMD64_MINGW, I386_MINGW

**Comment by VictorMiasnikov** [comment]
} Everything will be easier to be managed by just the pacman package manager

Microsoft ( or Microsoft friends) have alternative of pacman.

ToDo: add true name of alternative
