### ISSUE TITLE
Python2 deprecation

### ISSUE THREAD

**Issue by 3oheicrw** [modula3/cm3#1036]
You will have to convert your scripts to Python3 anyway but if you somehow can't, you could use Tauthon instead.
https://github.com/naftaliharris/tauthon

**Comment by 3oheicrw** [comment]
This issue was created because of outdated document. See https://github.com/modula3/cm3/issues/1033

**Comment by VictorMiasnikov** [comment]
} use Tauthon

There is interesting news. Thanks!
May be this method is useful.
