### ISSUE TITLE
Do we really need the full MSYS2 environment?

### ISSUE THREAD

**Issue by 3oheicrw** [modula3/cm3#1038]
I mean, we could get a standalone MinGW64 from winlibs.com and we could install a standalone version of Python, too. Do we really need the full MSYS2 environment?

**Comment by 3oheicrw** [comment]
Well, I forgot to check the scripts directory. It's a mess between shell scripts and Python scripts. So it seems a POSIX environment like Cygwin or MSYS2 is needed.

**Comment by VictorMiasnikov** [comment]
} we could get a standalone MinGW64 from winlibs.com
Not only from  winlibs.com. There are many alternatives.
} it seems a POSIX environment like Cygwin or MSYS2 is needed.
In short: not always. In case targets AMD64_NT , i386_NT even .py scripts doesn't need.
