### ISSUE TITLE
Why is there JScript code in batch file?

### ISSUE THREAD

**Issue by jpgpng** [modula3/cm3#1048]
https://github.com/modula3/cm3/blob/master/scripts/win/setup.cmd

**Comment by VictorMiasnikov** [comment]
I first time see / thinking about this file . . .

It looks like "history artifact"

**Comment by VictorMiasnikov** [comment]
About direct question:
> JScript code

Why not?  Can can use and .vbs scripts

**Comment by va0dl914** [comment]
Mixing jscript code in a batch file which is invalid batch file code renders this batch file will unable to run or just errorred out!

**Comment by VictorMiasnikov** [comment]
May be - I never use this file.I.e. is history artifact30.08.2022, 20:32, "va0dl914" ***@***.***>:
Mixing jscript code in a batch file which is invalid batch file code renders this batch file will unable to run or just errorred out!

**Comment by VictorMiasnikov** [comment]
I don't know -)I prefer Automate by Unisin for serious task / "scripting"30.08.2022, 20:30, "va0dl914" ***@***.***>:

About direct question:

JScript code

Why not? Can can use and .vbs scripts

But you can't mix vbs code in a batch file do you? It seems you are even not able to distinguish vb script from jscript 🤦
