### ISSUE TITLE
What does boot1.py do?

### ISSUE THREAD

**Issue by jpgpng** [modula3/cm3#1061]
How is it compared to concierge.py? And how to use it?

**Comment by VictorMiasnikov** [comment]
> What does boot1.py do? 

Create bootstrap of cm3.

> How is it compared to concierge.py?

Time to time concierge.py is best.
Time to time - boot1 + make + boot2

**Comment by VictorMiasnikov** [comment]
> And how to use it?

Please see examples in last issues related AMD64_MINGW and ( or) AMD64_CYGWIN.

**Comment by jpgpng** [comment]
> > What does boot1.py do?
> 
> Create bootstrap of cm3.

What kind of bootstrap? It bootstrap from precompiled source like concierge.py or it create that precompiled source?

**Comment by VictorMiasnikov** [comment]
Concierge.py do both job -) : it create bootstrap ( it named distributive) and "compile bootstap-disributive".Boot1.py and boot2.py work in pair.08.09.2022, 20:09, "jpgpng" ***@***.***>:


What does boot1.py do?

Create bootstrap of cm3.

What kind of bootstrap? It bootstrap from precompiled source like concierge.py or it create that precompiled source?

**Comment by VictorMiasnikov** [comment]
( possible dubl)Concierge.py do both job -) : it create bootstrap ( it named distributive) and "compile bootstap-disributive".Boot1.py and boot2.py work in pair.08.09.2022, 20:09, "jpgpng" ***@***.***>:


What does boot1.py do?

Create bootstrap of cm3.

What kind of bootstrap? It bootstrap from precompiled source like concierge.py or it create that precompiled source?
