### ISSUE TITLE
Support some obscure compilers

### ISSUE THREAD

**Issue by zpu2tw** [modula3/cm3#1065]
Embarcadero Compiler (Borland Compiler) and Open Watcom Compiler are both supported by cmake:
https://github.com/Kitware/CMake/tree/master/Modules/Compiler

**Comment by VictorMiasnikov** [comment]
I have try Watcom for cm3 for DOS.  It is too old -(

**Comment by zpu2tw** [comment]
> I have try Watcom for cm3 for DOS. It is too old -( for modern cm3 source code

There is Open Watcom V2 on github, just search for it. It's for Windows. Embarcadero Compiler is still updated, too.

**Comment by VictorMiasnikov** [comment]
I have O. v2 I don't remember exactly number of tested with  cm3 version 08.09.2022, 20:24, "zpu2tw" ***@***.***>:

I have try Watcom for cm3 for DOS. It is too old -( for modern cm3 source code

There is Open Watcom V2 on github, just search for it. It's for Windows. Embarcadero Compiler is still updated, too.
