### ISSUE TITLE
How to write binding to C library?

### ISSUE THREAD

**Issue by zpu2tw** [modula3/cm3#1067]
I want to use this C library: https://github.com/dbsoft/dwindows

As it's not very complex I prefer to write by hand (not using swig, but if it's needed I have no problems with it too).

**Comment by VictorMiasnikov** [comment]
IMHO, m3swig is more useful.

**Comment by zpu2tw** [comment]
> IMHO, m3swig is more useful.

It's useful for C++. This is plain C. Isn't that mean the C interface of yours is too complex for humans to write so need to depend on a machine generator?

**Comment by VictorMiasnikov** [comment]
In any key try m3swig  -) If You want, of course  -)08.09.2022, 20:21, "zpu2tw" ***@***.***>:

IMHO, m3swig is more useful.

It's useful for C++. This is plain C. Isn't that mean the C interface of yours is too complex for humans to write so need to depend on a machine generator?
