### ISSUE TITLE
What is the minimum version of Visual Studio supported?

### ISSUE THREAD

**Issue by zpu2tw** [modula3/cm3#1068]

**Comment by VictorMiasnikov** [comment]
VS 2012 for cm3 AMD64_NT.

VS 2008 ( and more, more early) for i386_NT

**Comment by VictorMiasnikov** [comment]
> VVM}}} VS 2012 for cm3 AMD64_NT.

But using VS 2012 require some changes inside config files.

VS 2015 . . 2002 should work with current settings.
