### ISSUE TITLE
What does quake do?

### ISSUE THREAD

**Issue by pwd96m4a** [modula3/cm3#1070]
Is .quake format a kind of import library so quake itself is the librarian?

https://github.com/modula3/cm3/tree/master/m3-win/import-libs/src

**Comment by VictorMiasnikov** [comment]
quake is part of cm3[.exe]

"quake" is "our Modila-3 cmake / make"

**Comment by pwd96m4a** [comment]
> quake is part of cm3[.exe]
> 
> "quake" is "our Modila-3 cmake / make"

How to use it?

**Comment by mikanystrom** [comment]
When you type the command "cm3" at your shell, you are "using" Quake...
what is your question??

**Comment by pwd96m4a** [comment]
> When you type the command "cm3" at your shell, you are "using" Quake... what is your question??

How to generate and how to use the import libraries like what on https://github.com/modula3/cm3/tree/master/m3-win/import-libs/src? It's weird. The file make-lib-1.cmd as the extension tells it's Windows Batch file but indeed it's a Perl script! From the other .cmd files it seems cl.exe (Microsoft MSVC Compiler) is required. So will these .quake import libraries work with MinGW too? It's a mess!

**Comment by VictorMiasnikov** [comment]
It is simple: _any_ .py / .cmd / .bat / Perl scripts use only on bootstrap step.  ( or for set up OS variables, etc. ) One time per life.In case AMD64_MINGW target all "GCC .a" linked by Quicke file  "AMD64_MINGW" from "config" folder.(   Running cl.exe try link and Microsoft .libs, but don't found they, write warning and continue work)10.09.2022, 06:06, "pwd96m4a" ***@***.***>:

When you type the command "cm3" at your shell, you are "using" Quake... what is your question??

How to generate and how to use the import libraries like what on https://github.com/modula3/cm3/tree/master/m3-win/import-libs/src? It's weird. The file make-lib-1.cmd as the extension tells it's Windows Batch file but indeed it's a Perl script! From the other .cmd files it seems cl.exe (Microsoft MSVC Compiler) is required. So will these .quake import libraries work with MinGW too? It's a mess!

**Comment by VictorMiasnikov** [comment]
P.S. Run utility FileMon.exe from SysInternals suite.Build Hello.exe first for AMD64_NT target.See process in running FileMon window (?).Repeat this for AMD64_MINGW.It is simplest way for investigate -)10.09.2022, 06:06, "pwd96m4a" ***@***.***>:

When you type the command "cm3" at your shell, you are "using" Quake... what is your question??

How to generate and how to use the import libraries like what on https://github.com/modula3/cm3/tree/master/m3-win/import-libs/src? It's weird. The file make-lib-1.cmd as the extension tells it's Windows Batch file but indeed it's a Perl script! From the other .cmd files it seems cl.exe (Microsoft MSVC Compiler) is required. So will these .quake import libraries work with MinGW too? It's a mess!

**Comment by mikanystrom** [comment]
As Victor said, the cmd/py/sh and whatnot is just for bootstrapping the
compiler. Since the compiler is written in Modula-3, and the quake
interpreter itself is part of the compiler, when bootstrapping the system
you have neither quake nor Modula-3 available. So it's special. That's like
any compiler written in itself, getting it set up the first time is always
going to involve some strange and tricky steps.

When you are using Modula-3 after it's installed, you code only in quake.
Most small programs require only a single file of that, and it's called
m3makefile and lives in the src directory. cm3 reads and executes the
commands in said m3makefile to know how to build and link your
program/library.

    Mika

**Comment by VictorMiasnikov** [comment]
Read as "running gcc.exe"10.09.2022, 10:57, ***@***.***" ***@***.***>:It is simple: _any_ .py / .cmd / .bat / Perl scripts use only on bootstrap step.  ( or for set up OS variables, etc. ) One time per life.In case AMD64_MINGW target all "GCC .a" linked by Quicke file  "AMD64_MINGW" from "config" folder.(   Running cl.exe try link and Microsoft .libs, but don't found they, write warning and continue work)10.09.2022, 06:06, "pwd96m4a" ***@***.***>:

When you type the command "cm3" at your shell, you are "using" Quake... what is your question??

How to generate and how to use the import libraries like what on https://github.com/modula3/cm3/tree/master/m3-win/import-libs/src? It's weird. The file make-lib-1.cmd as the extension tells it's Windows Batch file but indeed it's a Perl script! From the other .cmd files it seems cl.exe (Microsoft MSVC Compiler) is required. So will these .quake import libraries work with MinGW too? It's a mess!
