### ISSUE TITLE
How to conveniently run compiled binary after compilation?

### ISSUE THREAD

**Issue by jpgpng** [modula3/cm3#1083]
With gm2, it's just like gcc. You compile it with gm2 then ./binary (or just binary on Windows). With cm3, it's a bit more complicated as the binary was put in AMD64_MINGW directory (AMD64_MINGW/binary). I don't want to type the full AMD64_MINGW/binary just to run it. From what I saw on the file qinclude of m3-ui/qt I know quake could be told to call external program. Please help me add the needed code to m3makefile to automatically run the compiled binary after compilation. This means, when I typed cm3, it will compile the program and automatically run the compiled program for me. Thanks.

**Comment by RodneyBates** [comment]
On 9/19/22 08:51, jpgpng wrote:
>
> With gm2, it's just like gcc. You compile it with gm2 then ./binary (or just binary on Windows). With cm3, it's a bit more complicated as the binary was put in AMD64_MINGW directory (AMD64_MINGW/binary). I don't want to type the full AMD64_MINGW/binary just to run it. From what I saw on the file qinclude of m3-ui/qt I know quake could be told to call external program. Please help me add the needed code to m3makefile to automatically run the compiled binary after compilation. This means, when I typed cm3, it will compile the program and automatically run the compiled program for me. Thanks.
>
Quake has the "exec" function, (I believe a Quake builtin,) that
executes its arguments as a cli command.  On Linux, I have
lines in m3makefiles, like this example:

   exec("cd", "../../schutzcommon/src", ";", "make", "all")

**Comment by jpgpng** [comment]
I'm on Windows so I will wait for @VictorMiasnikov, perhaps he could give me something.

**Comment by VictorMiasnikov** [comment]
}  I don't want to type the full AMD64_MINGW/binary just to run itAre You run "cm3 -ship"?P.S.  > wait V.V.M.Thank of course, but I do "finishing works".It is tradition, simply ... Not only I ( VVM) -) can solve problems 19.09.2022, 19:29, "jpgpng" ***@***.***>:
I'm on Windows so I will wait for @VictorMiasnikov, perhaps he could give me something.

**Comment by VictorMiasnikov** [comment]
> } code to m3makefile to automatically run the compiled binary after compilation.( I am on smartphone. I try remember details, sorry for "less detailed answer")1)Inside cm3 "ecosystem" exist anolog of both bison and flex ( YACC/LEX). This files started with "k" letter, they has written in Calltech (?) ... m3makefile each of this contain running external ".exe" / binary file.2) You can look inside our "tests suite"It'is contain 100 .. 1000 folders with  e001 , p099 style naming of folders. This number 2 .. 3 subfolder by "total size"19.09.2022, 19:29, "jpgpng" ***@***.***>:
I'm on Windows so I will wait for @VictorMiasnikov, perhaps he could give me something.

**Comment by jpgpng** [comment]
> Are You run "cm3 -ship"?P.S.  > wait V.V.M.Thank of course, but I do "finishing works".It is tradition, simply ... Not only I ( VVM) -) can solve problems

During development you have to run your program to see if it works as expected or not. I will do my own batch script to help it. You Pascal family languages are weird. The Eiffel language, generated a ridiculously bloated in size exe using their very outdated gcc shipped with the installer package that even after you "finalize" it (note: a compilation technique by them) the executable size is still very large. The binary is also put on an obscure location in the project's very complicated directory structure that I have to use Windows search to find out. But, Eiffel language has an IDE called Eiffel Studio. You have no IDE! Perhaps you all using an advanced editor like vim or emacs that has built-in feature to run external binary so it's not a problem for you. I will try configuring CudaText to do so. But I always prefer to open a separate Command Prompt window and compile manually from there. The text editor's virtual terminal is never as good as a real one.

**Comment by jpgpng** [comment]
> code to m3makefile to automatically run the compiled binary after compilation.( I am on smartphone. I try remember details, sorry for "less detailed answer")1)Inside cm3 "ecosystem" exist anolog of both bison and flex ( YACC/LEX). This files started with "k" letter, they has written in Calltech (?) ... m3makefile each of this contain running external ".exe" / binary file.2) You can look inside our "tests suite"It'is contain 100 .. 1000 folders with  e001 , p099 style naming of folders. This number 2 .. 3 subfolder by "total size"

I didn't see anything like that. Perhaps I will wait until you can use your PC and could give me sth more clear.

**Comment by jpgpng** [comment]
The m3makefile approach is just too cumbersome. My batch script approach is much simpler. The only problem is you have to copy the batch file to the top of each of your project (assume you have a simple project, for things more complicated there must be a more complicated solution too) :smile:

**Comment by VictorMiasnikov** [comment]
> The m3makefile approach is just too cumbersome. My batch script approach is much simpler. The only problem is you have to copy the batch file to the top of each of your project (assume you have a simple project, for things more complicated there must be a more complicated solution too) 😄

"`Alles gut zum Ende gut`"  (engl. All's Well That Ends Well)

**Comment by VictorMiasnikov** [comment]
> > Are You run "cm3 -ship"?P.S.  > wait V.V.M.Thank of course, but I do "finishing works".It is tradition, simply ... Not only I ( VVM) -) can solve problems
> 
> During development you have to run your program to see if it works as expected or not. I will do my own batch script to help it. You Pascal family languages are weird. The Eiffel language, generated a ridiculously bloated in size exe using their very outdated gcc shipped with the installer package that even after you "finalize" it (note: a compilation technique by them) the executable size is still very large. The binary is also put on an obscure location in the project's very complicated directory structure that I have to use Windows search to find out. But, Eiffel language has an IDE called Eiffel Studio. You have no IDE! Perhaps you all using an advanced editor like vim or emacs that has built-in feature to run external binary so it's not a problem for you. I will try configuring CudaText to do so. But I always prefer to open a separate Command Prompt window and compile and run manually from there. The text editor's virtual terminal is never as good as a real one.

  There is small restructuration:
```
Eiffel /cm3 }}}  During development you have to run your program to see if it works as expected or not. 
Eiffel /cm3 }}} I will ( VVM: done on 2022-09-20) do my own batch script to help it. 

Eiffel bad }}} You Pascal family languages are weird. 
Eiffel bad }}}  The Eiffel language, generated a ridiculously bloated in size exe
Eiffel bad }}} using their very outdated gcc shipped with the installer package  
Eiffel bad }}} that even after you "finalize" it (note: a compilation technique by them) 
Eiffel bad }}} the executable size is still very large. 
Eiffel bad }}}  The binary is also put on an obscure location in the project's very complicated directory structure 
Eiffel bad }}} that I have to use Windows search to find out. 
Eiffel good}}} But, Eiffel language has an IDE called Eiffel Studio. 


cm3 bad }}}  You have no IDE! Perhaps you all using an advanced editor like vim or emacs 
cm3 bad }}} that has built-in feature to run external binary so it's not a problem for you. 
cm3 good}}} I will try configuring CudaText to do so. 

Eiffel bad }}} But I always prefer to open a separate Command Prompt window and compile and run manually from there. 
Eiffel bad }}} The text editor's virtual terminal is never as good as a real one.
```

But "cm3 ecosystem" has support using "a separate Command Prompt window" all time...

CudaText has support Modula-3 language.

**Comment by VictorMiasnikov** [comment]
P.S.

 When run this mini-"batch" file

`cmd /c PATH && cmd /c pause` 

are You see folder with cm3[.exe] in output?

**Comment by VictorMiasnikov** [comment]
P.P.S.

> You Pascal family language ( . . .)

 I prefer think about M3 as "M3/M2 family language".

(

  Please, see doctor F.Tkachov ( RIP :-( ) idea:

Pascal ( "classic") is Pascal-70 /  Pascal-68 (?).
Modula-2 is Pascal-79.
Oberon  is Pascal-85.

)

**Comment by jpgpng** [comment]
@VictorMiasnikov It turns out everything is easier than I think. I don't know why I messed this up in the first place. First, I inserted exec("dir") to know where is the current dir, it turns out it's already AMD64_MINGW. So what I have to do is just exec("binary") and done.

**Comment by jpgpng** [comment]
What is the different between exec and try_exec? What is the correct way to use try_exec? Where could I find the full document for quake and quake's built-in functions? Thanks.

**Comment by olaf-wagner** [comment]
On 21 Sep 2022, at 7:46, jpgpng wrote:

> What is the different between exec and try_exec? What is the correct 
> way to use try_exec? Where could I find the full document for quake 
> and quake's built-in functions? Thanks.
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/modula3/cm3/issues/1083#issuecomment-1253233958
> You are receiving this because you are subscribed to this thread.
>
> Message ID: ***@***.***>


The old website for cm3 at elego is still online it seems:
https://modula3.elegosoft.com/cm3/
I’m not sure if it has been replaced by something more advanced 
recently.
But you’ll find quake documentation there.

Olaf
-- 
Olaf Wagner -- elego Software Solutions GmbH -- http://www.elegosoft.com
                Gustav-Meyer-Allee 25 / Gebäude 12, 13355 Berlin, 
Germany
Geschäftsführer: Olaf Wagner | Sitz: Berlin
Handelregister: Amtsgericht Charlottenburg HRB 77719 | USt-IdNr: 
DE163214194

**Comment by jpgpng** [comment]
It seems the document is not fully migrated to github. The document on the old site is more abundant.

**Comment by mikanystrom** [comment]
Right, the compiler "runs" in the derived directory, so you can easily run
a just-build binary.

     Mika
