### ISSUE TITLE
How to handle Unicode strings on CM3?

### ISSUE THREAD

**Issue by jpgpng** [modula3/cm3#1086]
Assumed CM3 doesn't have built-in Unicode support. C is the same, too. So there are a bunch of C libraries whose purpose is just to add support for handling of Unicode strings to C. Could I make M3 bindings for such libraries and use it with CM3? Is there any easier solutions?

**Comment by VictorMiasnikov** [comment]
In fact CM3 does have built-in Unicode support.

**Comment by VictorMiasnikov** [comment]
N1086 is dubl-te ?

**Comment by VictorMiasnikov** [comment]
(...)

**Comment by VictorMiasnikov** [comment]
(...)

**Comment by VictorMiasnikov** [comment]
(...)

**Comment by VictorMiasnikov** [comment]
(...) N4 . . .

**Comment by VictorMiasnikov** [comment]
( Possible dubl)
Please look at https://github.com/modula3/cm3/pull/1087

**Comment by VictorMiasnikov** [comment]
`} Pull request https://github.com/modula3/cm3/pull/1087`

Are You see examples? They are good ( copmpile, running?) ?  

cp866 is OS DOS ( and 2 .. 15 countries) specific, may be

utf-8 is universal ( except DOS )

**Comment by jpgpng** [comment]
> `} Pull request https://github.com/modula3/cm3/pull/1087`
> 
> Are You see examples? They are good ( compile, running?) ?
> 
> cp866 is OS DOS ( and 2 .. 15 countries) specific, may be
> 
> utf-8 is universal ( except DOS )

Saw the examples. But didn't try to compile.
