### ISSUE TITLE
This is why cm3.cfg and cm3 itself always default to the NT host

### ISSUE THREAD

**Issue by 3oheicrw** [modula3/cm3#1104]
Even though it was built by MINGW thus expecting a MINGW host.

Hardcoded here: https://github.com/modula3/cm3/blob/master/m3-sys/cminstall/src/config/cm3.cfg

**Comment by 3oheicrw** [comment]
@VictorMiasnikov this is what you wanted to find out.

**Comment by VictorMiasnikov** [comment]
May be...

( I see on  https://github.com/VictorMiasnikov/cm3/actions/runs/3264401262 And Co.
In part of this we try work and with AMD64_MinGW )
