### ISSUE TITLE
I386_MINGW

### ISSUE THREAD

**Issue by s6nonqxt** [modula3/cm3#1115]
I did the same as this wiki: https://github.com/modula3/cm3/wiki/Getting-Started%3A-Windows

Except I replace mingw-w64-x86_64- with mingw-w64-i686- in package names to have 32 bit version and I used cm3-dist-I386_NT-d5.11.4.7z instead.

It failed to bootstrap.

**Comment by s6nonqxt** [comment]
Sorry everyone, it's documented in this very wiki that MinGW 32-bit doesn't work.

**Comment by VictorMiasnikov** [comment]
> it's documented in this very wiki that MinGW 32-bit doesn't work.

I did not known this.

I have cm3 I386_MINGW binaries
(  for example
cm3-min_by_concierge.py-I386_MINGW-d5.11.4-MINGW32(git-sdk-64@53940e3_and_{{i686-w64-mingw32-gcc-4.7.0}})-2021-11-19_17-16__Builded_by_VVM__2021-11-23_17-46__16bit__Unicode__cm3-221e0eb.7z 
)
