### ISSUE TITLE
Apple Silicon / ARM64_DARWIN support

### ISSUE THREAD

**Issue by dragisha** [modula3/cm3#1126]
Is there any work in progress on supporting this platform?

I did bootstrap compiler build and it runs on my M1 Pro MacBook... 

Target.m3... evolved... since I last worked on it :). Any hints on incorporating new platform?

**Comment by dragisha** [comment]
To complete this... The port is there already, just not obvious. It is using the C backend and I will see to document this and create a build host for CI on my laptop when I learn how.

**Comment by VictorMiasnikov** [comment]
I hope, You can use and LLVM13 as backend for this target

**Comment by dragisha** [comment]
Just got it all working, will definitely try with LLVM13. Thanks.

**Comment by VictorMiasnikov** [comment]
"LLVM13 backend" can build 99% of packages on AMD64_LINUX.

I have problems with rebuild LLVM13 by itself and with build compiler ( "cm3").

**Comment by VictorMiasnikov** [comment]
P.S. I approximate experience with cm3 AMD64_LINUX.

 I hope that using LLVM13 will successfull on MacOs
