### ISSUE TITLE
BITSIZE of "SET OF SomeEnumeration" has been made flexible? (C backend, ARM64_DARWIN)

### ISSUE THREAD

**Issue by dragisha** [modula3/cm3#1141]
Using ARM64_DARWIN with C backend and hit into a situation where BITSIZE(INTEGER) # BITSIZE(SET OF {A, B, C}).

I was using a lot of LOOPHOLE for interfacing libevent library with my Modula-3 code and it worked and works quite well with earlier (GCC backend) cm3 compilers on several platforms.

Is there a way to set old behavior with some switch to the current compiler?

**Comment by RodneyBates** [comment]
Sorry, I changed small sets to occupy the smallest of 8, 16, 32, or 64 that
will hold the value, because I have some very small sets that occur as fields
of objects with very high instance counts and didn't want so much space taken up

I'll look at making this optional.

**Comment by dragisha** [comment]
Please do not spend your time on this. I will create alternative for myself :).

Just push forward. Big thanks to you and other guys for keeping cm3 alive!
