### ISSUE TITLE
Modula-3 for Windows NT386 cm3-min-win*.* should contain mklib.exe

### ISSUE THREAD

**Issue by VictorMiasnikov** [modula3/cm3#200]
Problem:

```

 Short description:
...
'mklib' is not recognized as an internal or external command,
operable program or batch file.
"D:\cm3\bin\config\NT.common", line 1029: quake runtime error: library creation failed, see D:\cm3\src\m3-libs\sysutils\NT386\sysutils.lst for more information
...


Detailed  description:

  When run this command:
python upgrade.py && python do-cm3-all.py realclean skipgcc && python do-cm3-all.py buildship

we have error:
==
== package D:\cm3\src\m3-libs\sysutils ==

 +++ D:\cm3\bin\cm3.exe    -build -DROOT=D:/cm3/src +++
--- building in NT386 ---

ignoring ..\src\m3overrides

new source -> compiling EnvUtils.i3

 . . .
 
new source -> compiling FSUnixC.c
****  PARALLEL BACK-END BUILD, M3_PARALLEL_BACK = 20
new exporters -> recompiling FSUtils.i3
new exporters -> recompiling System.i3
new exporters -> recompiling PathRepr.i3
new exporters -> recompiling OSSpecials.i3
 -> archiving sysutils.lib
'mklib' is not recognized as an internal or external command,
operable program or batch file.
"D:\cm3\bin\config\NT.common", line 1029: quake runtime error: library creation failed, see D:\cm3\src\m3-libs\sysutils\NT386\sysutils.lst for more information


--procedure--  -line-  -file---
error              --  <builtin>
make_lib         1029  D:\cm3\bin\config\NT.common
Library            --  <builtin>
include_dir       117  D:\cm3\src\m3-libs\sysutils\src\m3makefile
                    5  D:\cm3\src\m3-libs\sysutils\NT386\m3make.args


Fatal Error: procedure "make_lib" defined in "D:\cm3\bin\cm3.cfg" failed.

 *** execution of [<function _BuildGlobalFunction at 0x000000000333DDD8>, <function _ShipFunction at 0x000000000333DE48>] failed ***

D:\cm3\src\scripts\python>
==

```

Solution:

cm3-min-win*.* should contain
mklib.exe
sysutils.dll

 Tested with:
cm3-min-win32-d5.11.0-VC90-20210312.zip

**Comment by jaykrell** [comment]
I agree about mklib, but why sysutils?
I mean, it's ok we can just throw stuff in, it won't make a big difference, but why?
I'm surprised either is missing.
(Really I'd like to remove mklib complete, but this wasn't trivial when I looked.)

**Comment by jaykrell** [comment]
I think mklib is in various boostraps. You or I should double check.

**Comment by VictorMiasnikov** [comment]
> mklib is in various bootstraps

 There is mklib.exe in bootstrap,
but there isn't mklib.exe in cm3-min-*.*  science 2015

**Comment by VictorMiasnikov** [comment]
> I agree about mklib, but why sysutils?

May by sysutils.dll isn't need. I am not testing this variant.

**Comment by coder5506** [comment]
The current status here: `mklib` is included in the bootstrap, *statically* linked, so there is no `sysutils.dll`.  I found that dynamic linking caused upgrades to fail--the dll would get replaced part way through, and the exe would no longer function--which is probably a separate issue, but at least this works now.

**Comment by VictorMiasnikov** [comment]
mklib.exe is need in any case...P.S. Bootstrap contain it, but *min* created by Phyton2 script doesn't contain.22.12.2021, 17:23, "Eric Sessoms" ***@***.***>:
Closed #200.

**Comment by jaykrell** [comment]
This is long standing design though I don't like it.
We should "never" install on top of self.
We should build/install to a new location, and then
the last step of "setup" should be just copy or untar or cpio.
And then cm3, mklib, etc. can be dynamically linked.

 - Jay

________________________________

**Comment by coder5506** [comment]
On Wed, Dec 22, 2021, at 5:41 PM, Jay Krell wrote:
> This is long standing design though I don't like it.
> We should "never" install on top of self.
> We should build/install to a new location, and then
> the last step of "setup" should be just copy or untar or cpio.
> And then cm3, mklib, etc. can be dynamically linked.

That is something I really don't like about the CM3 builds.  I'd like to do true out-of-tree builds, and I'd like building and installing to be two separate things, not all intertwingled as they are now.

So believe me when I say that is on my list.

**Comment by jaykrell** [comment]
Thank you very much Eric.

Can we discuss *briefly* automake/libtool vs. cmake for bootstrap?
I think it’d look *almost* the same but be more portable.

And having concierge.py work with python2 and 3?

Can we discuss briefly also using automake or cmake instead of the custom
m3build stuff?
I am willing for Msvc target to always be different. (Cmake is better for
Windows.)

I was using OSF/1 this year. Autotools made this easy. Cmake would have
been difficult/impossible.

Also fwiw Solaris was working this year. HP-UX and AIX and VMS would be
next on my list. HP-UX was working circa 2010.

The idea is basically to continue to reduce knowledge of any particular
Unix system.

 - Jay

**Comment by coder5506** [comment]
On Thu, Dec 23, 2021, at 7:21 PM, Jay Krell wrote:
> Can we discuss briefly also using automake or cmake instead of the custom m3build stuff?

Well, that is the direction I want to go with this.

I haven't had a chance yet to digest everything about m3build, so I may misspeak... but it sure looks to me like the whole quake/m3makefile thing was a mistake.  It was probably a good idea at the time--I can't criticize--but nowadays it's just an obstacle.  It makes too many assumptions about the context of usage, and so lacks flexibility.

So my hope here is to produce a pared-down frontend without all that baggage, which should then function like any other compiler and be usable from within autotools or cmake.  I think that will address just about all of the build issues.

But I haven't made this new frontend yet, because step #1 was just "get a repeatable build".

**Comment by jaykrell** [comment]
Something I never figured out, in terms of ease of integration into C build
& install structure is “like” the pkg directories and m3x files.
What do other systems do, to avoid parsing interface definitions multiple
times? And to provide instantiable generic code?
C & C++ do nothing.
C# and Java integrate parsed interfaces into binaries.
Go?
Rust?

Cm3 also has fine grained incremental build, though it has bugs, like if
you move files between packages.

And cm3 has that optional recompile more efficiently after discovering more
information.

Later,
 - Jay

**Comment by VictorMiasnikov** [comment]
> out-of-tree builds  In .pdb files we can see ( even in HEX editor) full path of correlated source code. This today "Phyton2 scripts" this is not be a big problem, but in case radical changes this will be a problem.23.12.2021, 19:28, "Eric Sessoms" ***@***.***>:
On Wed, Dec 22, 2021, at 5:41 PM, Jay Krell wrote:
> This is long standing design though I don't like it.
> We should "never" install on top of self.
> We should build/install to a new location, and then
> the last step of "setup" should be just copy or untar or cpio.
> And then cm3, mklib, etc. can be dynamically linked.

That is something I really don't like about the CM3 builds.  I'd like to do true out-of-tree builds, and I'd like building and installing to be two separate things, not all intertwingled as they are now.

So believe me when I say that is on my list.

**Comment by jaykrell** [comment]
The path to .pdb files in .dlls/.exes is not really related to out of tree builds.
You can do both either way.

My use of python2 I agree is not great.
 I wrote most of this over 10 years ago so don't be too annoyed with me?
I recently tried to make the code work with python3 but the compatibility problems were pretty significant in some places.
Eric's new code is Python3.
The failure of Python to maintain compatibility does bother me but the wider world seems to have moved on.

 - Jay
________________________________

**Comment by VictorMiasnikov** [comment]
>  "get a repeatable build". Please, see sub-problem with .pdb files / "Codeview" format "date for debuger"--  As small remark ( sorry: it doesn't look like "total political correct", but... Ok: I send it "as is". May be I will be edit something in future...)"quake/m3makefile" is not be a problem. We have more important ( and "more real") problems.I think that better solve they first.24.12.2021, 05:44, "Eric Sessoms" ***@***.***>:
On Thu, Dec 23, 2021, at 7:21 PM, Jay Krell wrote:
> Can we discuss briefly also using automake or cmake instead of the custom m3build stuff?

Well, that is the direction I want to go with this.

I haven't had a chance yet to digest everything about m3build, so I may misspeak... but it sure looks to me like the whole quake/m3makefile thing was a mistake.  It was probably a good idea at the time--I can't criticize--but nowadays it's just an obstacle.  It makes too many assumptions about the context of usage, and so lacks flexibility.

So my hope here is to produce a pared-down frontend without all that baggage, which should then function like any other compiler and be usable from within autotools or cmake.  I think that will address just about all of the build issues.

But I haven't made this new frontend yet, because step #1 was just "get a repeatable build".

**Comment by VictorMiasnikov** [comment]
We are "inside Github Issue #200".It always was a "tactic issue", related small disadvantage.I.e. I am not sure than this topic read all who want be known about "strategic things" / plans...  In any case curent state of "Cm3 ecosystem" has some "good things". I think that best way is non- radical chages.They can be even "relative small".--Phyton2/Phyton3 is example of "external dependency". As result, we have not only advantages of "Phyton world", but disadvantages too.24.12.2021, 13:04, "Jay Krell" ***@***.***>:
The path to .pdb files in .dlls/.exes is not really related to out of tree builds.
You can do both either way.

My use of python2 I agree is not great.
 I wrote most of this over 10 years ago so don't be too annoyed with me?
I recently tried to make the code work with python3 but the compatibility problems were pretty significant in some places.
Eric's new code is Python3.
The failure of Python to maintain compatibility does bother me but the wider world seems to have moved on.

 - Jay
________________________________

**Comment by jaykrell** [comment]
Python3 is a fine dependency. It is very heavily depended on in the world.

If I understand correctly, every Azure instance running Linux requires Python, for example.
  (Because of the "agent".)

Python2 is less fine. I can try again to remove it.
The dependency is kinda optional either way.
Python is being used to cd and run cm3.
Albeit the exact sequence and parameters are kinda tricky.
So we have the .sh and .cmd files too, but then they are less portable, slow, etc.

Ideally the code would work with 2 or 3. But Python does not maintain compatibility and they do not presently.
For example on OSF/1 we only have Python2.
But OSF/1 isn't important either.

I can try again to fix the Python2.

 - Jay

________________________________
