### ISSUE TITLE
Building for Win64 with VS2017

### ISSUE THREAD

**Issue by brakmic** [modula3/cm3#23]
Hello everyone,

Is it possible to build an **x64** version for **Win10x64** + **Visual Studio 2017**? 
I could create C sources with **./boot1.py AMD64_NT** but I don't know how to build them under VS2017. 
I had also tested the Windows Batch-Scripts from **scripts/win** but there I've got the error that the only supported archs were NT386 and GNU386.

Kind regards,

**Comment by jaykrell** [comment]
There is a Makefile in the boot output directory. Cd there and type nmake.

- Jay
________________________________

**Comment by brakmic** [comment]
Hi @jaykrell,

Many thanks. 

I've tried it with **nmake** but this is all I got:

```
(py27) d:\src\modula3\cm3\scripts\python\cm3-boot-AMD64_NT-d5.10.0-20171103>nmake Makefile

Microsoft (R) Program Maintenance Utility Version 14.11.25508.2
Copyright (C) Microsoft Corporation.  All rights reserved.

'Makefile' is up-to-date
```

**Comment by jaykrell** [comment]
Just nmake, not nmake makefile.

- Jay
________________________________

**Comment by brakmic** [comment]
I did it. However, it seems not to know how to compile *.io files.
