### ISSUE TITLE
Illegal recursive type overflows stack in m3front

### ISSUE THREAD

**Issue by demoitem** [modula3/cm3#43]
This program

MODULE Main;  
TYPE
  CC = RECORD
    a : RR;
    b : REF RR;
  END;
  RR = RECORD
    c : CC;
  END;
BEGIN
END Main.

correctly emits the illegal recursive type error but then
crashes by overflowing the stack. There seems to be a recursive loop in m3front between CheckAlign, AlignmentOK and IsAlignedOk.

**Comment by RodneyBates** [comment]
It is possible I have this fixed in branch "packedVars", which is incomplete but maybe usable.
I vaguely remember seeing & fixing a runaway recursion in the code.  I will try this example.

**Comment by RodneyBates** [comment]
Just checked.  My build of the head compiler segfaults on this case, but the one in
packedVars branch does not.

**Comment by demoitem** [comment]
That's good news.

It wasn't urgent. I can't see that branch on github. I think I can wait
until you merge it into main.

Regards Peter

**Comment by RodneyBates** [comment]
I see it on github, under the branch pulldown, "packedVars",, immediately below "master"

**Comment by demoitem** [comment]
Ok, got it, Don't know how I missed that.
Actually, there's a lot of ancient branches in that list. Are they useful?
I thought the theory was - you create a branch, play around with some new
code,
if it works then merge back into main, if not delete the branch. Either
way, the branch
is deleted.

**Comment by mikanystrom** [comment]
Well don't delete my coroutines!  I'm hoping to run this by some of the
people on this list soon, I think they are fully functional and could be
merged in.  I guess this means I am running it by the list right now :-)

**Comment by jcchu** [comment]
FWIW here’s another couple of defects related to (invalid) recursive types, hopefully also fixed in that branch.

1) TYPE T1 = ARRAY OF U1; U1 = T1
2) TYPE T2 = ARRAY [0..0] OF U2; U2 = T2

1) leads to an infinite recursion.  2) causes a division-by-zero error where apparently U2’s alignment is used as the divisor.

— JC

**Comment by demoitem** [comment]
fixed
