### ISSUE TITLE
Win32 backend crash with Long.LT

### ISSUE THREAD

**Issue by demoitem** [modula3/cm3#58]
This program - extracted from p240 - causes a crash in the code generator

TYPE
<*NOWARN*>TYPE UINT16 = Cstdint.uint16_t;

<*NOWARN*> VAR vu16:UINT16:=306;
<*NOWARN*> VAR vLC:LONGCARD:=307L;

<*NOWARN*>PROCEDURE uLT_var_LC_u16():BOOLEAN=
BEGIN 
  RETURN Long.LT(vLC,VAL(vu16, LONGINT));
END uLT_var_LC_u16;

***
*** runtime error:
***    <*ASSERT*> failed.
***    file "..\src\Codex86.m3", line 670
***

Stack trace:
   FP         PC      Procedure
---------  ---------  -------------------------------
0x10fe7c0   0x1c2827  binOp1 + 0x1d8 in ..\src\Codex86.m3
0x10fe8dc   0x1c2e15  binOp + 0x4bf in ..\src\Codex86.m3
0x10fe90c   0x1c1481  compare_double + 0x66 in ..\src\Codex86.m3
0x10fea24   0x1c2da7  binOp + 0x451 in ..\src\Codex86.m3
0x10feb78   0x1d6e36  dobin + 0x63d in ..\src\Stackx86.m3
0x10febbc   0x19e54b  compare + 0x7c0 in ..\src\M3x86.m3
0x10febe8   0x3af353  compare + 0x96 in ..\src\M3CG_Check.m3
0x10fec18   0x263ca1  Compare + 0xcd in ..\src\misc\CG.m3
0x10fec40   0x2cbe89  Compile + 0x1c6 in ..\NT386\LongLT.m3 => ..\src\builtinWord\LT.mg
0x10fec60   0x330d54  Compile + 0x83 in ..\src\exprs\CallExpr.m3
.........  .........  ... more frames ...

It may be related to the fact that the parms are globals. Other tests with LT and
locals seem to work.

**Comment by jaykrell** [comment]
Is this the integrated backend?
LLVM?
C?

**Comment by demoitem** [comment]
That was the integrated backend.

I never looked for a fix. It's a bit out of my comfort zone.
