### ISSUE TITLE
macOS: Compilation problems & solutions

### ISSUE THREAD

**Issue by brakmic** [modula3/cm3#59]
Hi,

Almost exactly a year ago I opened [an Issue](https://github.com/modula3/cm3/issues/46) documenting my problems with compilation under **macOS Mojave 10.14.1 (x64)**.

Thankfully, @mikanystrom helped me a lot so that in the end I was able to build a package that is [still available for download](https://github.com/modula3/cm3/issues/46#issuecomment-473415126) from my server. Malware reports are available as well, so you can be sure everything is clean.

Now, I have tried to do the same for **macOS Catalina 10.15.3 (x64)**. For this I used the currently available master sources and the bootstrap compiler was the one I built previously.

This time the compilation was much easier to accomplish and the few packages I had to remove from `pkginfo.txt` were a no-brainer. Here's [a patch](https://brakmic.com/download/txt/patch-cm3.diff) if you like to do the same on your local source. 

The affected files are:

```shell
newuoa caltech-other
magicextras caltech-other
boxes caltech-other
simplegrid caltech-other
router caltech-other
router-pauls caltech-other
router-pauls3 caltech-other
router-pauls4 caltech-other
gentest caltech-other
magraster caltech-other
mscheme m3-scheme
modula3scheme m3-scheme
schemereadline m3-scheme
mscheme-interactive m3-scheme
mscheme-interactive_r m3-scheme
```

The error messages I got when trying to compile those files were something like this:

```shell
== package /Users/brakmic/projects/cm3/caltech-other/gentest ==

 +++ /usr/local/cm3/bin/cm3    -build -override -DROOT=/Users/brakmic/projects/cm3 +++
--- building in AMD64_DARWIN ---

unable to read ../src/m3overrides, options "-override" and "-x" ignored.
"/Users/brakmic/projects/cm3/caltech-other/gentest/src/m3makefile", line 4: quake runtime error: unable to open "/usr/local/cm3/pkg/router/AMD64_DARWIN/.M3EXPORTS" for reading

--procedure--  -line-  -file---
import             --  <builtin>
include_dir         4  /Users/brakmic/projects/cm3/caltech-other/gentest/src/m3makefile
                    5  /Users/brakmic/projects/cm3/caltech-other/gentest/AMD64_DARWIN/m3make.args

Fatal Error: package build failed
 *** execution of [<function _BuildLocalFunction at 0x104699848>] failed ***
```

The **m3-scheme**-files, however, would actually compile at first, but when I later tried to build a package with `do-cm3-all.py buildship` errors like these were thrown:

```shell
****  PARALLEL BACK-END BUILD, M3_PARALLEL_BACK = 20
 -> archiving libscheme-lib.a
 ==> /Users/brakmic/projects/cm3/m3-scheme/scheme-lib done

== package /Users/brakmic/projects/cm3/m3-scheme/mscheme ==

 +++ /usr/local/cm3/bin/cm3    -build -override -DROOT=/Users/brakmic/projects/cm3 +++
--- building in AMD64_DARWIN ---

"/Users/brakmic/projects/cm3/m3-scheme/mscheme/AMD64_DARWIN/../src/m3overrides", line 2: quake runtime error: unable to open "/Users/brakmic/projects/cm3/m3-scheme/mscheme/AMD64_DARWIN/../src/../../m3overrides" for reading

--procedure--  -line-  -file---
include            --  <builtin>
                    2  /Users/brakmic/projects/cm3/m3-scheme/mscheme/AMD64_DARWIN/../src/m3overrides

Fatal Error: package build failed
 *** execution of [<function _BuildLocalFunction at 0x106150848>] failed ***
```

So I removed them from `pkginfo.txt` as well. 

#### The packages are available for download from my server. Have fun!

-----
* [cm3-all-AMD64_DARWIN-d5.10.0-Darwin19.3.0-20200310.tar.gz](https://brakmic.com/download/tar/cm3-all-AMD64_DARWIN-d5.10.0-Darwin19.3.0-20200310.tar.gz)
* [Malware Report](https://www.virustotal.com/gui/file/88ba6c9e9a864c1681d5792a9f6fb1a1c337d8452d49f5100bbccce64046582d)

-----

* [cm3-min-AMD64_DARWIN-d5.10.0-Darwin19.3.0-20200310.tar.gz](https://brakmic.com/download/tar/cm3-min-AMD64_DARWIN-d5.10.0-Darwin19.3.0-20200310.tar.gz)
* [Malware Report](https://www.virustotal.com/gui/file/d3889751b7c9bbe47dbf81542debc1f07b47dd8cd8a80e4ebf71ba0dd7b90997)
------

Regards

**Comment by mikanystrom** [comment]
OK, what did I break now..... any idea why this isn't working for you?  I
compile on AMD64_LINUX and it seemed to work fine there.

(All the packages you listed are ones I have added over the last year or
two.)

      Mika

**Comment by brakmic** [comment]
Maybe it's because there were no such files in the previous compiler location? The errors above point at files that should be inside the bootstrap compiler. But because this one didn't have those new files the compilation obviously failed. 

```shell

line 2: quake runtime error: unable to open "/Users/brakmic/projects/cm3/m3-scheme/mscheme/AMD64_DARWIN/../src/../../m3overrides" for reading
```

**Comment by jaykrell** [comment]
Try deleting the scripts/PKGS file?
It will get recreated.
I don't think that will help though.
I disabled a lot of the caltech packages on non-AMD64-LINUX.
This isn't a super interesting problem to fix, but I guess we should.

**Comment by VictorMiasnikov** [comment]
Are you see this?
https://github.com/modula3/cm3/discussions/654#discussioncomment-868831

**Comment by coder5506** [comment]
I don't think this issue is any longer relevant, especially as the referenced patches and downloads are no longer available.  For anyone still following, there is a new [macOS release](https://github.com/modula3/cm3/wiki/Getting-Started:-macOS).

**Comment by FranklinChen** [comment]
Thanks, the new release builds great!
