### ISSUE TITLE
Update README to explain how to install a release

### ISSUE THREAD

**Issue by tkurtbond** [modula3/cm3#655]
It has been long years since I've installed a CM3 release, and I can't figure out how to install the AMD64_DARWIN release.  A short explanation in the README would help greatly.

**Comment by VictorMiasnikov** [comment]
> } how to install the AMD64_DARWIN release.

 Are You see this?
https://github.com/modula3/cm3/issues/59#issue-578606517

**Comment by tkurtbond** [comment]
That doesn't say anything about how to install the AMD64_DARWIN release from the release tar files.

I found [this](https://github.com/modula3/cm3/releases/tag/unix64le-d5.11.1-20210610) more helpful, though building libm3core.a [failed](https://github.com/modula3/cm3/discussions/654#discussioncomment-868831).

**Comment by jaykrell** [comment]
The m3core/dtoa problem is fixed now.
Maybe someone else can write better documentation?

**Comment by coder5506** [comment]
[macOS](https://github.com/modula3/cm3/wiki/Getting-Started:-macOS) install directions are now available on the wiki.  I'm not sure I'm prepared to touch the README.
