### ISSUE TITLE
How to build from scratch?

### ISSUE THREAD

**Issue by markjreed** [modula3/cm3#7]
Every one of the scripts seems to try to run "cm3" at some point.  I have no cm3. I have no Modula-3 compiler of any sort.  How do I build one?

**Comment by darko20** [comment]
Download and use one of the compiler binaries in the releases section on
github. If you need more help, ask on the mailing list.

**Comment by jaykrell** [comment]
We are close to being able to start with "just" a C or C++ compiler, but 1 we aren't there yet 2 you could ask the same question about it, but people don't realize that -- C compiler has same bootstrapping problem/solution -- old binaries or cross build using old binaries.

 - Jay

**Comment by metacore** [comment]
release cm3 for Windows is missing

**Comment by jaykrell** [comment]
I'll try to build another release this week.

You need either an old native compiler or a cross compiler. Same as with anything else EXCEPT said compiler is for Modula-3, not the more typicalC or C++.

I would like to change it -- you'll still need a C/C++ compiler though.

 - Jay

**Comment by jaykrell** [comment]
Note: I have put up a release and a "bootstrap".
The binary releases are *very* tied to the particular C compiler/runtime they use.There isn't much to do about that I think, except:

The "bootstrap" archives have no such dependency.

The bootstrap archive could be more friendly and thorough,i.e. it should provide the entire system not just cm3/mklib.Its Makefile is not incremental.
https://github.com/modula3/cm3/releaseshttps://github.com/modula3/cm3/releases/tag/d5.10.0-20160106https://github.com/modula3/cm3/releases/tag/untagged-f4a25522e7215ba257e6
 - Jay


From: jay.krell@cornell.edu
CC: cm3@noreply.github.com; jay.krell@cornell.edu
Subject: Re: [cm3] How to build from scratch? (#7)
Date: Fri, 25 Dec 2015 13:56:16 -0800
To: reply@reply.github.com

I'll try to build another release this week.
You need either an old native compiler or a cross compiler. Same as with anything else EXCEPT said compiler is for Modula-3, not the more typicalC or C++.
I would like to change it -- you'll still need a C/C++ compiler though.
 - Jay
On Dec 25, 2015, at 7:51 AM, metacore <notifications@github.com> wrote:

release cm3 for Windows is missing
