### ISSUE TITLE
Loophole problem in C backend

### ISSUE THREAD

**Issue by demoitem** [modula3/cm3#748]
With this simple M3
  v := 1.23D0;   
  t := LOOPHOLE(v,LONGINT);
  x := LOOPHOLE(t,LONGREAL);

the C backend generates for the first loophole

(the HTML is converting asterix to some unprintable char. Press edit to see the correct stmts below)

```
(*(INT64*)((120)+(char*)(&Main_m_M_Main_L_29)))=
(INT64)( ((INT64)(((double)(*((double*)(INT64_(104)+((ADDRESS)(&Main_m_M_Main_L_29)))))))));
```

and for the second loophole

```
(*(double*)((112)+(char*)(&Main_m_M_Main_L_29)))=
(double)( ((double)(((INT64)(*((INT64*)(INT64_(120)+((ADDRESS)(&Main_m_M_Main_L_29)))))))));
```

but this is incorrect. It can be fixed by replacing the  cast double with INT64 in the first one thus

```
(*(INT64*)((120)+(char*)(&Main_m_M_Main_L_29)))=
(INT64)( ((INT64)(((INT64)(*((INT64*)(INT64_(104)+((ADDRESS)(&Main_m_M_Main_L_29)))))))));
```

and INT64 with double in the second

```
(*(double*)((112)+(char*)(&Main_m_M_Main_L_29)))=
(double)( ((double)(((double)(*((double*)(INT64_(120)+((ADDRESS)(&Main_m_M_Main_L_29)))))))));
```

then it works.

This might go some way to fixing grisu problems.

**Comment by coder5506** [comment]
I haven't figured out how to fix this yet, but it's pretty clear that "loophole" is only generating a cast.  Breaking down the generated C code:

```c
(*(INT64*)((112)+(char*)(&Main_m_M_Main_L_9)))=(INT64)(  // assign an INT64
((INT64)( // after casting to INT64
((double)(*((double*)(INT64_(104)+((ADDRESS)(&Main_m_M_Main_L_9))))))))); // a double
```

i.e., that's TRUNC.  I would expect loophole to look more like

```c
(*(INT64*)((112)+(char*)(&Main_m_M_Main_L_9)))=(INT64)(  // assign an INT64
((INT64)( // after casting to INT64
*(INT64*)& // reinterpret the bits
((double)(*((double*)(INT64_(104)+((ADDRESS)(&Main_m_M_Main_L_9))))))))); // a double
```

And, indeed that seems to be the case
https://github.com/modula3/cm3/blob/master/m3-sys/m3back/src/M3C.m3#L7287

So basically the current implementation of loophole is incomplete and probably just a placeholder.  I'll keep working on it.

**Comment by coder5506** [comment]
@jaykrell I just wanted to mention that I am planning to try to fix this issue, mainly as a learning exercise, to help me learn my way around the C backend.  I don't think you need to address it specifically unless you just get tired of waiting on me.

**Comment by jaykrell** [comment]
I am tired of waiting on me.
A new person renews my wait. :)
Thank you!

**Comment by jaykrell** [comment]
What loophole is supposed to do, is cast pointers, not values.
In psuedo code, my intent, I am not claiming I didn't make mistakes, _like_:
```
int i;
float f = loophole(i);
```
is supposed to become:
```
int i;
float f = *(float*)&i;
```

I wrote this stuff so long ago, but what I wonder is, "Are their temporaries?" either from the frontend or the backend?
We need something to take the address of.

**Comment by coder5506** [comment]
> "Are their temporaries?"

That's the main thing I haven't figured out yet.  So yeah, we need to cast pointers, but we can't take the address of an arbitrary expression, so who is responsible for the temporaries?

It had not occurred to me it could be an issue with the frontend.  The rabbit-hole goes deeper...

**Comment by jaykrell** [comment]
Now that I look closer in the discussion, this case does not need temporaries.

**Comment by jaykrell** [comment]
Now that someone is looking at the C backend:
 -  It is one file, sorry.
 -  It is kinda dumb and string based, but part way toward being a little more type-ful, and the end, still just string-based.
Like..there is kinda sorta an IR in there, but we do so little or nothing with it, that it is unproven and wasteful. By "IR" I mean arrays and structs (or objects) and not just strings. I wrote it in about a month. The bug tail was sort of short/small. Ignoring this part.
  - It is self-hosting.
 -  Modula-3 lacks a C preprocessor. (it isn't quite one file, notice the "MultiPass" stuff I added, tedious).
 -  Being warning-free across a spectrum of compilers, is indeed a pain. Compilers warn for the darnest things.
 -  It works with OSF native cc/CC, Solaris native cc/CC, and the usual modern suspects gcc/clang/msvc.
 - If you have AIX xlC, please let me know. Or anything EDG based.
  
 Maybe write up some documentation? Not that the rest of Modula-3 implementation is documented.
 Or maybe I'm just making too much of it, nothing interesting here, move along..

**Comment by jaykrell** [comment]
Actually there are kinda two IRs, but one proved valuable.
There is a direct representation of the M3CG calls -- Modula-3 only having a call-based IR, persisted to gcc, but not persisted (in memory) otherwise.

Also notice how all the files concatenatable, including with m3core's hand written .h/.c (m3core.h first).

Also notice..debugging is bad. Needs work..Needs higher level field-based IR from frontend, or deduce it.
Need to layout structs with fields, not arrays of bytes (there is a bug there, for bitfields...).

**Comment by coder5506** [comment]
> Maybe write up some documentation?

Happy to document as I go.  I have that newbie perspective that lets me see what's not obvious.

> Being warning-free across a spectrum of compilers, is indeed a pain. Compilers warn for the darnest things.

I'll do my best not to break this, but I don't have access to a lot of variety for testing.  Linux and MacOS (Intel) at home, and I can get FreeBSD or Windows in the cloud, but that's it.  Other than that, I'm basically trying to keep changes very conservative.

**Comment by jaykrell** [comment]
The warnings thing was not a warning to you. It was me boasting. Don't worry about it.
We don't have CI. So you/I/we are blameless. And if get CI, you/I/we will be gated appropriately.
If you have any "DevOps" friends, please send them our way. :)

**Comment by jaykrell** [comment]
I even used the lack of CI as an excuse to remove the workarounds for older gcc that I put in.
Trying to whittle down the code a bit, cleaner, less messy, more amenable to newbiew and oldies, etc. :)

**Comment by jaykrell** [comment]
(It should still compile with old gcc, just issue warnings.)

**Comment by coder5506** [comment]
015d905 fixes the specific conversions mentioned in this issue.  There remain loophole bugs in the C backend that I haven't sorted out yet, but those are covered by test p047.  So I'm not sure whether to keep the issue open or let the failing test be our guide.

**Comment by demoitem** [comment]
Well done. I'd close the issue and let p047 be the basis of further fixes.
The loophole operator is tricky and not well documented.

**Comment by coder5506** [comment]
It's a plan.
