### ISSUE TITLE
prepare new bugfix release

### ISSUE THREAD

**Issue by coder5506** [modula3/cm3#752]
Recent changes to master mean that HEAD no longer builds on the 5.11.1 release from June, and most likely does not build on the 5.11.2 release from July (though I haven't been able to personally verify).

I'm looking forward to everything I'll get to learn trying to put together a new release, but I would not object if anybody wanted to drop me some hints.

**Comment by jaykrell** [comment]
Please see scripts\python\make-dist.py.
Just try running it.
It should drop a bunch of promising stuff in $TMP.

It is mostly but not entirely well done.

It requires some amount of working cm3/m3core/mklib.
It makes a copy of them.
It builds min, all, and maybe in between. They overlap.
They are just tgz, and then very simple .deb and .msi.
But maybe we should drop the .deb and .msi.

There is also provision elsewhere (boot1.py?) for making a "distribution" of sorts that is just one large .c file, that compiles to cm3. But, it gives some compilers grief -- too large. It was an achievement, to get all the types to line up, but maybe not good in the end.

I would like to make something autoconf, automake based. And when I say autoconf, I just mean, "find the C++ compiler" and maybe let user chose installation. The system is statically "configured" already to run "everywhere", for some point in time definition.

But anyway, make-dist.py.

boot1.py can also make a bunch of .cpp files bootstrap.

**Comment by coder5506** [comment]
I probably closed this issue a bit early.  To be clear, I tested this release as best I could by hand, but that's hard to keep track of.  I can't guarantee that it all works, but I'm planning to integrate it into my CI work as soon as I can, and if the CI reveals any problems with these builds I will fix them.  Also, having suffered through making one release by hand, I can see a path toward automating the releases with the CI, so I'll be working on that soon.
