### ISSUE TITLE
unix64le: CM3 fails to build on Linux aarch64 (Raspberry Pi 4, Ubuntu 20.04) with GCC 10 or Clang

### ISSUE THREAD

**Issue by Pawlicker** [modula3/cm3#756]
CM3 (d5.11.3-20211007) fails to build on the Raspberry Pi 4, running aarch64/ARM64 Linux using the unix64le files. 

When building CM3 and making an empty config file/one just saying to use the C backend, using the instructions on the 20210610 build:

$ g++-10 -g -pthread -c cm3-boot-unix64le-d5.11.3-20211007.cpp
../src/Wrx86.m3: In function ‘int SockAddrNativeToM3(const NativeSockAddrUnionAll*, M3SockAddrUnionAll*)’:
../src/Wrx86.m3:6671: warning: control reaches end of non-void function [-Wreturn-type]
$ g++-10 -g -pthread -o cm3 cm3-boot-unix64le-d5.11.3-20211007.o
$ ./cm3
cm3: ../src/Wrx86.m3:2064: const char* MxConfigC__HOST(): Assertion `strcmp(M3_HOST, result) == 0' failed.
Aborted (core dumped)

When trying to build the rest of CM3, I get this:

lain@RPI4:~/Downloads/cm3/cm3-unix64le-d5.11.1-20210610/scripts/python$ ./boot2min.py c
SearchPath return:/opt/cm3/bin/cm3
Traceback (most recent call last):
  File "./boot2min.py", line 17, in <module>
    import os, sys, pylib
  File "/home/lain/Downloads/cm3/cm3-unix64le-d5.11.1-20210610/scripts/python/pylib.py", line 660, in <module>
    if TargetOnlyHasCBackend(Target):
  File "/home/lain/Downloads/cm3/cm3-unix64le-d5.11.1-20210610/scripts/python/pylib.py", line 385, in TargetOnlyHasCBackend
    a = a.lower()
AttributeError: 'NoneType' object has no attribute 'lower'

When I use Clang++ instead of GCC:
lain@RPI4:~/Downloads/cm3$ clang++ -g -pthread -c cm3-boot-unix64le-d5.11.3-20211007.cpp
../src/unix/Common/Upwd.i3:494:1: error: 'sched_yield' is missing exception specification 'throw()'
sched_yield(void);
^
                  throw()
../src/thread/PTHREAD/ThreadPThread.i3:3668:1: note: previous declaration is here
sched_yield(void);
^
1 error generated.

uname -a output:
`lain@RPI4:~/Downloads/cm3$ uname -a
Linux RPI4 5.4.0-1044-raspi #48-Ubuntu SMP PREEMPT Thu Sep 9 15:24:01 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux`

Compiler versions:
`lain@RPI4:~/Downloads/cm3$ g++-10 --version
g++-10 (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.`

`lain@RPI4:~/Downloads/cm3$ clang++ --version
clang version 10.0.0-4ubuntu1 
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
lain@RPI4:~/Downloads/cm3$`

**Comment by coder5506** [comment]
Thanks for trying?  :)

Your main problem seems to be this:

> $ ./cm3
cm3: ../src/Wrx86.m3:2064: const char* MxConfigC__HOST(): Assertion `strcmp(M3_HOST, result) == 0' failed.
Aborted (core dumped)

I don't have access to aarch64 to test on, but for now I'm going to assume this is a problem with the build and see if I can reproduce it on another platform.  I may need to come back and ask you for more details.

The other issues:  I've seen Ubuntu barf like that when you install "python27" or "python2", instead of just "python".  I can't explain why.  It could also be subsequent to the first error.  As for clang, we're still playing catch-up there, so I'd prefer to concentrate on getting it working with g++.

**Comment by Redfoxymoon** [comment]
Linux on 64-bit arm reports aarch64 not arm64 which causes problems.

**Comment by Pawlicker** [comment]
I can confirm this fix works to build boot2min.py, however the giant CPP file and MxConfigC.c need to be patched as well, or else the bootstrap will overwrite the working compiler with the broken one. Here's the result:

$ cm3 --version
Critical Mass Modula-3 version d5.11.4
  GitInfo: https://github.com/modula3/cm3.git/commit/890a4d8afe330ea733023ba84b84247f9d6d64ac
           https://github.com/modula3/cm3.git/commits/master
           remote: https://github.com/modula3/cm3.git
           revision: 890a4d8afe330ea733023ba84b84247f9d6d64ac
           branch: master
  last updated: 2021-10-07
  compiled: 2021-10-10 19:37:13
  configuration: /opt/cm3/bin/cm3.cfg
  host: ARM64_LINUX
  target: ARM64_LINUX

**Comment by Pawlicker** [comment]
> Hopefully this gets the bootstrap a little further along.

It actually builds boot2min and works. However when running `./do-cm3-all.py buildship c` the backend fails with an assert failed message. After trying the same C backend setup on AMD64 Ubuntu 20.04, I can also confirm this happens on there as well and created a bug for it (#758) as this is an unrelated bug that happens on the unix64le C backend setup on AMD64 as well.

**Comment by VictorMiasnikov** [comment]
( "for history")

https://github.com/modula3/cm3/issues/758#issuecomment-941734651
> I can confirm that using the old tarball with the fixed bootstrap (after adding LINUX_ARM64 and editing MxConfigC.c to include the fix for that platform) works great, and the entire distribution was able to successfully build. The only thing I had to do was install mariadb's libraries for those to build as well.
