### ISSUE TITLE
default array parameters fail to compile across module boundaries (was M3C.m3 runtime error (<*ASSERT*> failed: current_proc # NIL))

### ISSUE THREAD

**Issue by Pawlicker** [modula3/cm3#758]
When I attempted to run do-cm3-all.py using the new CM3 C backend to build the distribution, the building failed when m3c got to m3-libs/realgeometry. Once I bypassed this the same error halted building at m3-ui/ui. Initially I got this message on ARM64 Ubuntu, however once I tested it on AMD64 Ubuntu 20.04 with the same build setup the same error popped up.

~/Downloads/CM3/cm3/m3-libs/realgeometry$ cm3
--- building in AMD64_LINUX ---

ignoring ../src/m3overrides

new source -> compiling RealPoint.i3
new source -> compiling RealTransform.i3
new source -> compiling RealInterval.i3
new source -> compiling RealRect.i3
new source -> compiling RealPath.i3

***
*** runtime error:
***    <*ASSERT*> failed: current_proc # NIL 
***    file "../src/M3C.m3", line 6422
***

Aborted (core dumped)

uname -a: 
$ uname -a
Linux Shoutmon 5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

CM3 version:
$ cm3 --version
Critical Mass Modula-3 version d5.11.4
  GitInfo: https://github.com/modula3/cm3.git/commit/f9f1617a8c89cbbb2d078d85d9888a8683602a0b
           https://github.com/modula3/cm3.git/commits/master
           remote: https://github.com/modula3/cm3.git
           revision: f9f1617a8c89cbbb2d078d85d9888a8683602a0b
           branch: master
  last updated: 2021-10-07
  compiled: 2021-10-11 15:00:18
  configuration: /opt/cm3/bin/cm3.cfg
  host: AMD64_LINUX
  target: AMD64_LINUX

**Comment by VictorMiasnikov** [comment]
Good news:
 https://github.com/modula3/cm3/commit/8098c080e5f78067d294fcabe0052bf1503e3a3e#commitcomment-57888996

 P.S. IMHO, it can sense rename "Subj" of this issue.

**Comment by coder5506** [comment]
Currently seems to break the C, GCC, and LLVM backends.

**Comment by coder5506** [comment]
Appears to be resolved in fe79f6c9b1a3c34a1d5cb8523b7167f0ec0f570c
