### ISSUE TITLE
aarch64 not recognised target

### ISSUE THREAD

**Issue by MarcusE1W** [modula3/cm3#805]
Hi.
Thanks for the great work here.

From the last release note I take it that cm3 should work with ARM (aarch64)?
To try I have downloaded release `cm3-dist-AMD64_LINUX-d5.11.4.tar.xz` hoping that might fit.

When I run `../cm3-dist-AMD64_LINUX-d5.11.4/scripts/concierge.py install --prefix $HOME/cm3 all` I get this error immediately:

> AARCH64_LINUX is not a recognized target

I noticed that some scripts refer to ARM64 instead of AARCH64, could that be the problem ?

With:
- Pinebook Pro (aarch64)
- Manjaro ARM

I have followed the instructions for [Linux](https://github.com/modula3/cm3/wiki/Getting-Started%3A-Linux), Is there anything else I need to do to install on aarch64 ?

**Comment by coder5506** [comment]
That is the right download, and that's the expected command.

Sometimes when the scripts fail to correctly detect the platform, you can help it along by being explicit.  In this case, by adding `--target ARM64_LINUX` to the install command.

```shell
../cm3-dist-AMD64_LINUX-d5.11.4/scripts/concierge.py install --prefix $HOME/cm3 all --target ARM64_LINUX
```

(The scripts do try to normalize AARCH64 to ARM64, internally.)

Unfortunately our CI only runs on Ubuntu https://app.circleci.com/pipelines/github/modula3/cm3/24/workflows/8b7fd951-e232-4429-ba3e-98f122b15c9c/jobs/23 but that doesn't require the target hint https://github.com/modula3/cm3/blob/master/.circleci/config.yml#L35 so I'm not sure why Manjaro is different.  I don't have any way to test that.

**Comment by MarcusE1W** [comment]
Thanks. That worked for that error.

Unfortunately a bit later there was another one:
This is the extract around where the error occurred.

```
-d5.11.4 -DTARGET=ARM64_LINUX -DM3_BACKEND_MODE=C
--- building in ARM64_LINUX ---

ignoring ../src/m3overrides

"/home/mmw/Downloads/cm3-dist-AMD64_LINUX-d5.11.4/m3-libs/m3core/ARM64_LINUX/m3make.args", line 5: quake runtime error: cannot assign to readonly variable: TARGET old:AARCH64_LINUX new:ARM64_LINUX

--procedure--  -line-  -file---
                    5  /home/mmw/Downloads/cm3-dist-AMD64_LINUX-d5.11.4/m3-libs/m3core/ARM64_LINUX/m3make.args

Fatal Error: package build failed
Traceback (most recent call last):
  File "/home/mmw/Downloads/build/../cm3-dist-AMD64_LINUX-d5.11.4/scripts/concierge.py", line 1816, in <module>
    Concierge().main()
  File "/home/mmw/Downloads/build/../cm3-dist-AMD64_LINUX-d5.11.4/scripts/concierge.py", line 1750, in main
    command.execute()
  File "/home/mmw/Downloads/build/.
```

I do have some results by this time in folder `~/cm3/bin`
> cm3  cm3.cfg  config  mklib

cm3 can be executed and `cm3 --version` gives:

```
--- building in AARCH64_LINUX ---

cm3: found nothing to build.
[mmw@PBP bin]$ ./cm3 --version
Critical Mass Modula-3 version d5.11.4
  GitInfo: /commit/2c6d45f2df0237ca7d4629f7825669db634e5910
           /commits/
           remote: 
           revision: 2c6d45f2df0237ca7d4629f7825669db634e5910
           branch:
  last updated: 2021-10-07
  compiled: 2022-01- 2 17:33:51
  configuration: ./cm3.cfg
  host: ARM64_LINUX
  target: AARCH64_LINUX
```

**Comment by coder5506** [comment]
I can't even guess where that's coming from.  Literally the only place in the source that AARCH64 is mentioned, it is only there to map to ARM64.

Could you look around to find the target definition?

```shell
grep -r 'readonly TARGET = "AARCH64_LINUX"' .
grep -r 'readonly TARGET = "AARCH64_LINUX"' ~/cm3
```

And though I think it's unlikely to be a remnant of the earlier attempt, it's probably worth clean-slating.  Nuke everything before trying again: ~/cm3, your build directory, and the unpacked sources.

**Comment by MarcusE1W** [comment]
So, In good old computer fashion i have deleted everything and did it again and it work.
Thanks a lot for the help.
I think the last issue was due to my initial unsuccessful attempts to compile the release.

To sum up, adding `--target ARM64_LINUX` as described above made it work.
