### ISSUE TITLE
Problems building HEAD

### ISSUE THREAD

**Issue by dragisha** [modula3/cm3#9]
I have: 
Critical Mass Modula-3 version d5.9.0
  last updated: 2010-07-21
  compiled: 2014-08-19 18:12:27
  configuration: /usr/local/cm3/bin/cm3.cfg
  host: AMD64_LINUX
  target: AMD64_LINUX

When doing a ./make-bin-dist-min.sh, newly built cm3 breaks when moment comes to rebuild everything with it.

----------------------------------------------------------------------------
stage 3: compiling libraries using new cm3 compiler
----------------------------------------------------------------------------

/root/cm3/scripts/do-cm3-core.sh buildlocal
/root/cm3/scripts/pkgmap.sh -c "/var/tmp/cm3/bin/cm3 -build -override -DROOT='/root/cm3'" import-libs m3core libm3 windowsResources parseparams patternmatching sysutils unittest m3middle m3objfile m3linker m3back m3cggen m3quake m3front m3scanner m3tools m3cgcat m3bundle mklib tempfiles bitvector digraph realgeometry set slisp sortedtableextras table-list tcp cm3ide mtex m3sleep cm3 m3cc
=== package /root/cm3/m3-win/import-libs ===
 +++ /var/tmp/cm3/bin/cm3 -build -override -DROOT='/root/cm3' +++
/bin/sh: line 1: 20979 Segmentation fault      /var/tmp/cm3/bin/cm3 -build -override -DROOT='/root/cm3'
 *** execution of /var/tmp/cm3/bin/cm3 -build -override -DROOT='/root/cm3' failed ***

When I start it from gdb, I see this:

Program received signal SIGSEGV, Segmentation fault.
__longjmp () at ../sysdeps/x86_64/__longjmp.S:56
56		jmpq *%rdx
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.166.el6_7.7.x86_64
(gdb) bt
#0  __longjmp () at ../sysdeps/x86_64/__longjmp.S:56
#1  0xa933bd60cb76afa4 in ?? ()
Cannot access memory at address 0xa926bd60cb76afa4

Is there some way to get around this? Some known stable release?

TIA,
dd

**Comment by darko20** [comment]
Something to do with this perhaps?

https://github.com/modula3/cm3/commit/57ad34f5034d5000bd5d63fb384851921bc782a1

You should ask on the list, from what I can tell not many people get these
messages.

**Comment by dragisha** [comment]
List does not work for me at this moment... As maintenance page is down, I cannot check it.
Do you have some binary package, recent, for AMD64_DARWIN? And/or ARM_LINUX? :)
I am rebuilding cm3 world because I need to do some work on raspberry pi and I would like very much to do it in Modula-3 :)
TIA

**Comment by dragisha** [comment]
What can be interesting... I have crashes on AMD64_LINUX (with above approach but also when doing a bootstrap archive) and with AMD64_DARWIN.

**Comment by darko20** [comment]
I have a Raspberry Pi binary, if that will help, I'll upload it to releases.

I think my current Darwin compiler is no more recent than what is on
releases here, which you uploaded. If I build something it will probably
have the same problem. Have you tried building using an earlier commit
(like the one before that change)?

A shortcut for getting the zipped source for a particular commit is:

https://github.com/modula3/cm3/archive/{commit-sha}.zip

**Comment by dragisha** [comment]
Thank you for raspberry pi binary, it will solve my current problem! As for just-before-change binary, it looks like it is only a revert of previous change... I will try to get some older revision, thanks for a hint!

**Comment by darko20** [comment]
If you build a more recent binary for the RaPi, please upload a package to
releases so I can use it too!

**Comment by dragisha** [comment]
Of course. Thanks!

**Comment by dragisha** [comment]
FYI, I have just built AMD64_DARWIN binary package based on e0bfe8c from jan 6. Jay tagged e0bfe8c and uploaded NT386 and I386_DARWIN (???) releases for it.

**Comment by dragisha** [comment]
temporarily fixed.

**Comment by jaykrell** [comment]
Did you try upgrade.py instead? I don't use the script you used, the way to build this change is a bit delicate as it changes compiler/runtime interface.

 - Jay
