### ISSUE TITLE
Win32Pathname.LastBase is incorrect.

### ISSUE THREAD

**Issue by jaykrell** [modula3/cm3#937]
Posix Pathname.LastBase(a.b.c/d.e.f) appears to be d.e correct
Win32 Pathname.LastBase(a.b.c/d.e.f) appears to be d incorrect

They both work from the end of the strong but Posix only look for one dot, Win32 keeps looking.

This code should be refactored to avoid so much duplication.

**Comment by jaykrell** [comment]
Should be ok now?

**Comment by VictorMiasnikov** [comment]
} Should be ok now?

 Tested by build AMD64_NT with:
1)
python boot2min.py c AMD64_NT
 +
boot1.py AMD64_NT c keep commands
nmake

 2) again run
python boot2min.py c AMD64_NT 

 3)  Todo: will be tested by
python upgrade.py && python do-cm3-all.py realclean skipgcc && python do-cm3-all.py buildship
